const date = new Date()
// console.log(date)
// console.log(date.toLocaleString())
// console.log(date.toString())
// console.log(date.toDateString())
// console.log(date.toISOString())
// console.log(typeof(date))
console.log(Math.floor(Date.now()/1000))
console.log(date.getMonth())
console.log(date.getDay())